### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'PLEASE CHMOD

### ISSUE THREAD

**Issue by may29adil** [PHPSocialNetwork/phpfastcache#256]
Hello,

i am getting the following error, i gave the permission but still the error is same. 

URL http://s584354718.onlinehome.us/RaasCollection_new/ 

Fatal error: Uncaught exception 'Exception' with message 'PLEASE CHMOD /kunden/homepages/4/d584354717/htdocs/..//s584354718.onlinehome.us- - 0777 OR ANY WRITABLE PERMISSION!' in /homepages/4/d584354717/htdocs/RaasCollection_new/phpfastcache/3.0.0/phpfastcache.php:250 Stack trace: #0 /homepages/4/d584354717/htdocs/RaasCollection_new/phpfastcache/3.0.0/phpfastcache.php(191): phpFastCache::htaccessGen('/kunden/homepag...', true) #1 /homepages/4/d584354717/htdocs/RaasCollection_new/phpfastcache/3.0.0/phpfastcache.php(115): phpFastCache::getPath(false, Array) #2 /homepages/4/d584354717/htdocs/RaasCollection_new/phpfastcache/3.0.0/phpfastcache.php(32): phpFastCache::getAutoClass(Array) #3 /homepages/4/d584354717/htdocs/RaasCollection_new/class/class_Menu.php(59): phpFastCache() #4 /homepages/4/d584354717/htdocs/RaasCollection_new/header.php(241): class_Menu->DisplayLadieswearMenu('Ladieswear') #5 /homepages/4/d584354717/htdocs/RaasCollection_new/index.php(28): require_once('/homepages/4/d5...') #6 {main} thrown in /homepages/4/d584354717/htdocs/RaasCollection_new/phpfastcache/3.0.0/phpfastcache.php on line 250

**Comment by khoaofgod** [comment]
found the problem, will fix it tonight togther with others bugs.

**Comment by may29adil** [comment]
just wondering if you fix the code ?

**Comment by Geolim4** [comment]
It'll be fixed in the next release with some others bugs, just be patient ;)

**Comment by Pansa237** [comment]
I have just tested this:

Latest release,  6.0.0-rc2,  6bfaa5d, Verified, 6.0.0-rc2 Release
Geolim4 released this 29 days ago

I still get the same error, although folders have chmod 777.

Error message:
Fatal error: Uncaught phpFastCache\Exceptions\phpFastCacheIOException: PLEASE CREATE OR CHMOD /cache/subfolder/Files - 0777 OR ANY WRITABLE PERMISSION!

Can somebody tell me in which release this has been or will be fixed?

**Comment by Geolim4** [comment]
Hello @Pansa237,

Can you open your own issue please ? :)
Also try to chmod recursively using "-r"  argument.

Cheers,
Georges
