### ISSUE TITLE
Couchbase Error

### ISSUE THREAD

**Issue by rdecourtney** [PHPSocialNetwork/phpfastcache#517]
### Configuration:

PhpFastCache version: 7
PHP version: 7.1.10
Operating system: Windows 2008 R2 X64

When using the Couchbase driver on a vanilla install of the last version of PHPFASTCACHE, I'm getting the error:

Couchbase\Cluster::__construct() expects exactly 1 parameter, 3 given Error File: W:\web\localuser\competency.io\competency.io\assets\plugins\phpFastCache.v7\src\phpFastCache\Drivers\Couchbase\Driver.php Error Line: 149

Changing it from:
 $this->instance = new CouchbaseClient("couchbase://{$host}", $username, $password);

to:
 $this->instance = new CouchbaseClient("couchbase://{$host}");

Fixed the issue

**Comment by Geolim4** [comment]
Hello,

The V7 is still on development.
But thanks I'll take a look soin.

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello,

What couchDB client are you using ??
I'm not able to reproduce this bug using phpfastcache/couchdb package.
We forked it for performance reasons and because the author does not maintains his package anymore.

Cheers,
Georges

**Comment by Geolim4** [comment]
Ohhh my bad, wrong driver, waking up is hard...
Indeed my IDE just caught a signature mismatch...

**Comment by Geolim4** [comment]
Can you try to replace phpFastCache/Drivers/Couchbase/Driver.php by this:

https://gist.github.com/Geolim4/d76177c5ec3bf2b66fb2109455e381b2

And tell me if it work ? (With or without cluster password and with or without bucket password)

Thanks you very much.

**Comment by rdecourtney** [comment]
Absolutely ok George :-) 

When using that Driver.php - I'm getting the error:

Error Message: Undefined index: username
Error File: W:\web\localuser\competency.io\competency.io\assets\plugins\phpFastCache.v7\src\phpFastCache\Drivers\Couchbase\Driver.php
Error Line: 86

I'm not defining the username in the config when calling getInstance... if I do define it, then there's no error.. 

$cache_instance = CacheManager::getInstance('couchbase', [
			'host' => '127.0.0.1',
			'username' => '',
			'port' => '8091',
			'timeout' => '1',
			'buckets' => [
				[
				  'bucket' => 'default',
				  'password' => ''
				],
			  ]
		]);

**Comment by Geolim4** [comment]
This notice should not appears oO
Can you post me the content of your phpFastCache/Core/Pool/DriverBaseTrait.php please ?

Can you please also confirm explicitly that:
- The cluster username and password works with a provided ones ?
- The bucket password works with a provided one ?

Thanks.

**Comment by Geolim4** [comment]
@rdecourtney I'm gonna push a fix soon, can you please have a look at my previous answer please ?

Thanks you very much.

**Comment by Geolim4** [comment]
@rdecourtney Bump :)

**Comment by rdecourtney** [comment]
Hi G, sorry, was away on Canadian Thanksgiving.. will do now

**Comment by rdecourtney** [comment]
<?php
/**
 *
 * This file is part of phpFastCache.
 *
 * @license MIT License (MIT)
 *
 * For full copyright and license information, please see the docs/CREDITS.txt file.
 *
 * @author Khoa Bui (khoaofgod)  <khoaofgod@gmail.com> http://www.phpfastcache.com
 * @author Georges.L (Geolim4)  <contact@geolim4.com>
 *
 */

namespace phpFastCache\Core\Pool;

use phpFastCache\Core\Item\ExtendedCacheItemInterface;
use phpFastCache\Exceptions\phpFastCacheInvalidArgumentException;
use phpFastCache\Exceptions\phpFastCacheLogicException;


/**
 * Class DriverBaseTrait
 * @package phpFastCache\Cache
 */
trait DriverBaseTrait
{
    use ExtendedCacheItemPoolTrait;

    /**
     * @var array default options, this will be merge to Driver's Options
     */
    protected $config = [];

    /**
     * @var bool
     */
    protected $fallback = false;

    /**
     * @var mixed Instance of driver service
     */
    protected $instance;

    /**
     * @var string
     */
    protected $driverName;

    /**
     * @param $config_name
     * @param string $value
     */
    public function setup($config_name, $value = '')
    {
        /**
         * Config for class
         */
        if (is_array($config_name)) {
            $this->config = array_merge($this->config, $config_name);
        } else {
            $this->config[ $config_name ] = $value;
        }
    }

    /**
     * @return array
     */
    public function getConfig()
    {
        return $this->config;
    }


    /**
     * @return mixed
     */
    public function getConfigOption($optionName)
    {
        if (isset($this->config[ $optionName ])) {
            return $this->config[ $optionName ];
        } else {
            return null;
        }
    }

    /**
     * Encode data types such as object/array
     * for driver that does not support
     * non-scalar value
     * @param $data
     * @return string
     */
    protected function encode($data)
    {
        return serialize($data);
    }

    /**
     * Decode data types such as object/array
     * for driver that does not support
     * non-scalar value
     * @param $value
     * @return mixed
     */
    protected function decode($value)
    {
        return @unserialize($value);
    }

    /**
     * Check phpModules or CGI
     * @return bool
     */
    protected function isPHPModule()
    {
        return (PHP_SAPI === 'apache2handler' || strpos(PHP_SAPI, 'handler') !== false);
    }


    /**
     * @param $class
     * @return bool
     */
    protected function isExistingDriver($class)
    {
        return class_exists("\\phpFastCache\\Drivers\\{$class}");
    }


    /**
     * @param $tag
     * @return string
     */
    protected function _getTagName($tag)
    {
        return "__tag__" . $tag;
    }

    /**
     * @param \phpFastCache\Core\Item\ExtendedCacheItemInterface $item
     * @return array
     */
    public function driverPreWrap(ExtendedCacheItemInterface $item)
    {
        $wrap = [
          self::DRIVER_DATA_WRAPPER_INDEX => $item->get(),
          self::DRIVER_TAGS_WRAPPER_INDEX => $item->getTags(),
          self::DRIVER_EDATE_WRAPPER_INDEX => $item->getExpirationDate(),
        ];

        if ($this->config[ 'itemDetailedDate' ]) {
            $wrap[ self::DRIVER_MDATE_WRAPPER_INDEX ] = new \DateTime();
            /**
             * If the creation date exists
             * reuse it else set a new Date
             */
            $wrap[ self::DRIVER_CDATE_WRAPPER_INDEX ] = $item->getCreationDate() ?: new \DateTime();
        } else {
            $wrap[ self::DRIVER_MDATE_WRAPPER_INDEX ] = null;
            $wrap[ self::DRIVER_CDATE_WRAPPER_INDEX ] = null;
        }

        return $wrap;
    }

    /**
     * @param array $wrapper
     * @return mixed
     */
    public function driverUnwrapData(array $wrapper)
    {
        return $wrapper[ self::DRIVER_DATA_WRAPPER_INDEX ];
    }

    /**
     * @param array $wrapper
     * @return mixed
     */
    public function driverUnwrapTags(array $wrapper)
    {
        return $wrapper[ self::DRIVER_TAGS_WRAPPER_INDEX ];
    }


    /**
     * @param array $wrapper
     * @return \DateTime
     */
    public function driverUnwrapEdate(array $wrapper)
    {
        return $wrapper[ self::DRIVER_EDATE_WRAPPER_INDEX ];
    }

    /**
     * @param array $wrapper
     * @return \DateTime
     */
    public function driverUnwrapCdate(array $wrapper)
    {
        return $wrapper[ self::DRIVER_CDATE_WRAPPER_INDEX ];
    }


    /**
     * @param array $wrapper
     * @return \DateTime
     */
    public function driverUnwrapMdate(array $wrapper)
    {
        return $wrapper[ self::DRIVER_MDATE_WRAPPER_INDEX ];
    }

    /**
     * @return string
     */
    public function getDriverName()
    {
        if(!$this->driverName){
            $this->driverName = ucfirst(substr(strrchr((new \ReflectionObject($this))->getNamespaceName(), '\\'), 1));
        }
        return $this->driverName;
    }

    /**
     * @param \phpFastCache\Core\Item\ExtendedCacheItemInterface $item
     * @return bool
     * @throws phpFastCacheLogicException
     */
    public function driverWriteTags(ExtendedCacheItemInterface $item)
    {
        /**
         * Do not attempt to write tags
         * on tags item, it can leads
         * to an infinite recursive calls
         */
        if (strpos($item->getKey(), self::DRIVER_TAGS_KEY_PREFIX) === 0) {
            throw new phpFastCacheLogicException('Trying to set tag(s) to an Tag item index: ' . $item->getKey());
        }

        if(!$item->getTags() && !$item->getRemovedTags())
        {
            return true;
        }

        /**
         * @var $tagsItems ExtendedCacheItemInterface[]
         */
        $tagsItems = $this->getItems($this->getTagKeys($item->getTags()));

        foreach ($tagsItems as $tagsItem) {
            $data = $tagsItem->get();
            $expTimestamp = $item->getExpirationDate()->getTimestamp();

            /**
             * Using the key will
             * avoid to use array_unique
             * that has slow performances
             */

            $tagsItem->set(array_merge((array)$data, [$item->getKey() => $expTimestamp]));

            /**
             * Set the expiration date
             * of the $tagsItem based
             * on the older $item
             * expiration date
             */
            if ($expTimestamp > $tagsItem->getExpirationDate()->getTimestamp()) {
                $tagsItem->expiresAt($item->getExpirationDate());
            }
            $this->driverWrite($tagsItem);
            $tagsItem->setHit(true);
        }

        /**
         * Also update removed tags to
         * keep the index up to date
         */
        $tagsItems = $this->getItems($this->getTagKeys($item->getRemovedTags()));

        foreach ($tagsItems as $tagsItem) {
            $data = (array)$tagsItem->get();

            unset($data[ $item->getKey() ]);
            $tagsItem->set($data);

            /**
             * Recalculate the expiration date
             *
             * If the $tagsItem does not have
             * any cache item references left
             * then remove it from tagsItems index
             */
            if (count($data)) {
                $tagsItem->expiresAt(max($data));
                $this->driverWrite($tagsItem);
                $tagsItem->setHit(true);
            } else {
                $this->deleteItem($tagsItem->getKey());
            }
        }

        return true;
    }

    /**
     * @param $key
     * @return string
     */
    public function getTagKey($key)
    {
        return self::DRIVER_TAGS_KEY_PREFIX . $key;
    }

    /**
     * @param $key
     * @return array
     */
    public function getTagKeys(array $keys)
    {
        foreach ($keys as &$key) {
            $key = $this->getTagKey($key);
        }

        return $keys;
    }

    /**
     * @param string $optionName
     * @param mixed $optionValue
     * @return bool
     * @throws phpFastCacheInvalidArgumentException
     */
    public static function isValidOption($optionName, $optionValue)
    {
        if (!is_string($optionName)) {
            throw new phpFastCacheInvalidArgumentException('$optionName must be a string');
        }

        return true;
    }

    /**
     * @return array
     */
    public static function getRequiredOptions()
    {
        return [];
    }

    /**
     * @return array
     */
    public static function getValidOptions()
    {
        return [];
    }
}

**Comment by rdecourtney** [comment]
I tested with the default bucket in Couchbase (I'm only using the Memcache Feature) that worked with no authentication. It also worked with a defined bucket with a password.

If I don't define a bucket though in the getInstance - it complains about an undefined index:

\phpFastCache.v7\src\phpFastCache\Drivers\Couchbase\Driver.php Error Line: 94

It also complains if 'username' isn't defined..

**Comment by Geolim4** [comment]
Ok, i get it the notice is completely normal at this moment since the v7 is still in development and something is not yet updated in that file I asked you to paste :)

**Comment by Geolim4** [comment]
I pushed some commits, can you test now if everything is ok ?
Thanks !!

**Comment by rdecourtney** [comment]
Downloaded the entire 519 version... still getting that driver error (that you can see at: https://competency.io/dev/cache/ )

When using this configuration

$cache_instance = CacheManager::getInstance('couchbase', [
	'host' => '127.0.0.1',
	'username' => '',
	'password' => '',
	'port' => '8091',
	'timeout' => '1',
	'buckets' => [
		[
		  'bucket' => 'default', // The bucket name, generally "default" by default
		  'password' => '' // The bucket password if there is
		],
	  ]
]);

When removing the $username and $password from that line, the error stops (but then I'm not using a username and password on the dev caching server)...

Thanks G!

**Comment by rdecourtney** [comment]
It would be REALLY useful as well to either have a changelog or version file in the root directory. When downloading each version, I've got 5-6 folders with phpfastcache in it, and no idea what version or how up-to-date they are... thanks!

**Comment by Geolim4** [comment]
In fact, the changelog is already present in release page:
https://github.com/PHPSocialNetwork/phpfastcache/releases

But the V7 is currently in development and no release has been yet released.
If you plan to integrate PhpFastCache on production, I suggest you to use the v6 instead (final branch).
As you can see here:
https://github.com/PHPSocialNetwork/phpfastcache/blob/v7/src/phpFastCache/Drivers/Couchbase/Driver.php#L77

The bug has been fixed for the V7, but I need you to validate these changes before I made them on v6 too.

Cheers,
Georges

**Comment by rdecourtney** [comment]
Hi Georges... as above... the error still exists in the current build (7d5e91e) with the code setup for Couchbase Memcached Driver - no username / password / default bucket (standard install) :-)

**Comment by Geolim4** [comment]
You got the wrong version, the PR #519 fixes the #518 x)
Download the latest v7 here: 
https://github.com/PHPSocialNetwork/phpfastcache/archive/v7.zip

It includes this line that fix the php notice you got:
https://github.com/PHPSocialNetwork/phpfastcache/blob/120234d3271fbd3cdcaf8d112825ac99edc54f4b/src/phpFastCache/Core/Pool/DriverBaseTrait.php#L72

**Comment by rdecourtney** [comment]
Downloaded the v7 and works great, I can remove all connection info, change the host to non existent, all works great, with entering no information, it defaults gracefully. The only thing that I can't get to fail is the port. I'm running Couchbase memcache server on port 11211 - but if I change that in getInstance to port 1 for example, it will not fail, it still connects to the server - using a bad IP address will not connect (as it should).

**Comment by Geolim4** [comment]
Is the Couchbase default port 8091 ?

**Comment by Geolim4** [comment]
Try to "hardcode" the port here to see if it fails:
https://github.com/PHPSocialNetwork/phpfastcache/blob/120234d3271fbd3cdcaf8d112825ac99edc54f4b/src/phpFastCache/Drivers/Couchbase/Driver.php#L82

Should looks like:
```php
             $this->instance = new CouchbaseClient("couchbase://{$clientConfig['host']}:8091"); 
```

**Comment by Geolim4** [comment]
Bump @rdecourtney 😄

**Comment by Geolim4** [comment]
@rdecourtney I'm gonan close this issue? Just give me a feedback if you can, else I'll have to add a note related to the port :)

Thanks you !

**Comment by Geolim4** [comment]
Here's your changelog on V7 & V6 for now (v5 will come later... Many release...)

**Comment by rdecourtney** [comment]
Afternoon Georges, 

Sorry for the late response.. not been at work :-) 

I've tried hard-coding the correct, and incorrect ports in and it connects, or fails appropriately.. however, when calling it through 'getInstance' and specifying the port, it's not failing and connecting as default to 8091, when it should fail.

Specifically - this /SHOULD/ fail, but doesn't:

$cache_instance = CacheManager::getInstance('couchbase', [
	'host' => '127.0.0.1',
	'port' => '1',
	'timeout' => '1',
	'buckets' => [
		[
		  'bucket' => 'default',
		  'password' => ''
		],
	  ]
]);

(and thank you for the changelog!!  🍺 )

**Comment by Geolim4** [comment]
In fact, currently the port is not used by PFC onCouchbase.
This is why I asked you to test hardcoding the port:
https://github.com/PHPSocialNetwork/phpfastcache/issues/517#issuecomment-336598368

Currently Couchbase seems to not offer the possibility to change the port :(

I'll assume that configuring the port is not possible at this moment.

Thanks you very much !

**Comment by rdecourtney** [comment]
Sounds good! Let me know if there's anything else I can help with..

**Comment by Geolim4** [comment]
I would not miss it :)

Cheers,
Georges.L

**Comment by Geolim4** [comment]
I made a fix that should allow you to setup the port, with a default port to 8091 :)
