### ISSUE TITLE
Deprecated Message Shown by PHP

### ISSUE THREAD

**Issue by hsnfirdaus** [PHPSocialNetwork/phpfastcache#848]
**Configuration**
- **PhpFastCache version:** 8.1.0
- **PhpFastCache API version:** 3.0.0
- **PHP version:** 8.1.2
- **Operating system:** Arch Linux x86_64 (Kernel: 5.16.2-arch1-1)

**Describe the bug**

Getting this deprecated message:
```
Deprecated:  Return type of Phpfastcache\Util\ArrayObject::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/htdocs/v2/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Util/ArrayObject.php on line 52

Deprecated:  Return type of Phpfastcache\Drivers\Files\Item::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/htdocs/v2/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Core/Item/ItemExtendedTrait.php on line 339
```

- Using Psr16Adapter with files driver

**Comment by Geolim4** [comment]
Hello,

I have pushed a fix for Phpfastcache 8.1 (with PHP 8.1), but I strongly encourage you to upgrade to Phpfastcache 9.0.

I won't release a new version immediately so you might want to use "v8.x-dev" channel on composer.

Cheers,
Georges.

**Comment by Awilum** [comment]
@Geolim4 Unfortunately this issue still reproduced, please add `#[\ReturnTypeWillChange]`
https://github.com/PHPSocialNetwork/phpfastcache/issues/846#issuecomment-1004766170

**Comment by Awilum** [comment]
@Geolim4 please check this 
https://php.watch/versions/8.1/ReturnTypeWillChange
https://php.watch/versions/8.1/internal-method-return-types#ReturnTypeWillChange

**Comment by Geolim4** [comment]
I just pushed fixes today, see commit above !

**Comment by Awilum** [comment]
I see. Waiting for new release with this fixes

**Comment by Geolim4** [comment]
I won't make a new release soon, use `"v8.x-dev"` meanwhile.

**Comment by huqedato** [comment]
Sadly, the issue still persisting with Php v8.1.3 and PhpFastCache v8.1.0 
```
<br />
<b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>106</b><br />
<br />
<b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>115</b><br />
<br />
<b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>130</b><br />
<br />
<b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>48</b><br />
<br />
<b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>56</b><br />
<br />
<b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>80</b><br />
<br />
<b>Deprecated</b>:  Return type of Phpfastcache\Drivers\Redis\Item::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Core/Item/ItemExtendedTrait.php</b> on line <b>438</b><br />
<br />
```

**Comment by Geolim4** [comment]
> Sadly, the issue still persisting with Php v8.1 and PhpFastCache v7
> 
> ```
> <br />
> <b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>106</b><br />
> <br />
> <b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>115</b><br />
> <br />
> <b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>130</b><br />
> <br />
> <b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>48</b><br />
> <br />
> <b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>56</b><br />
> <br />
> <b>Deprecated</b>:  Return type of Phpfastcache\Util\ArrayObject::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Util/ArrayObject.php</b> on line <b>80</b><br />
> <br />
> <b>Deprecated</b>:  Return type of Phpfastcache\Drivers\Redis\Item::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/server/public_html/includes/vendor/cache/lib/Phpfastcache/Core/Item/ItemExtendedTrait.php</b> on line <b>438</b><br />
> <br />
> ```

That normal, v7 is no longer supported, please upgrade at least to v8.1.

[Read the Wiki](https://github.com/PHPSocialNetwork/phpfastcache/wiki/%5BV4%CB%96%5D-Global-support-timeline#v71-september-2019)

**Comment by apoca** [comment]
@Geolim4 weird but I have PHP 8.1 and phpfastcahe 8.1.X and I got the same issues above, lots of deprecated functions in PHP8.1 as an example: Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated

**Comment by Geolim4** [comment]
> mb_strlen

Which version are you using ?

**Comment by apoca** [comment]
I've solved. My bad... I'm using 8.1.4 and I've cleaned my sentry plataforma for this project and I didn't catch anymore any deprecated function. Thanks.
